
executer:
	gcc comparer_matrice.c -o exec -lm
	./exec


sign:
	gcc signer_matrice.c -o exec -lm
	./exec

generation_graph:
	gcc generation_graph.c -o exec -lm
	./exec
	
executer_deprecated:
	gcc comparer_martice_naif.c -o exec -lm
	./exec
sign_copy_deprecated:
	gcc signer_copy.c -o exec -lm
	./exec

